### ISSUE TITLE
Unable to restore-as production tpac table to sbsgui 1.0.0 on staging

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/imem#90] opened 2016-06-17 12:49 UTC
tpac_20160617.zip

is checked in

it stops at row 3500 without any error message

looks like a (session ?)  timeout

@c-bik if you don't see it directly, you can assingn to to shamis

**Comment by stoch** [comment] 2016-06-17 12:54
I could add the subsequent rows 3501.. 3649 with copy/paste from prod without issues. Seems no tto be a problem of the snapshot data.

**Comment by stoch** [comment] 2016-06-17 12:57
I vaguely remember Walter (on our request) to implement a timeout in DDerl in order to avoid orphan FSMs and imem sessions. That must be the culprit.

**Comment by stoch** [comment] 2016-06-17 12:59
The timeout may occur on the imem level too (restore_as being an imem function).

**Comment by c-bik** [comment] 2016-06-17 12:59
@stoch looking into it right away. if session is a problem then calling snap_restore function of meta directly will go through to the end

**Comment by c-bik** [comment] 2016-06-17 13:41
Works at snapshot interface level:
```erlang
(sbsgui@oltapmos-sbsh02.it.bwns.ch)2> imem_snap:restore_as(bkp,tpac,tpacProd,destroy,false).
15:27:19.263 [info] [_IMEM_] {imem_snap,541} restore properties of tpacProd
15:27:20.698 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 500 rows
15:27:22.071 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 1000 rows
15:27:23.397 [warning] [_SBS_] {sbs_wss,13} No sbs session found, disconnecting websocket
15:27:23.490 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 1500 rows
15:27:24.364 [warning] [_SBS_] {sbs_wss,13} No sbs session found, disconnecting websocket
15:27:24.973 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 2000 rows
15:27:25.363 [warning] [_SBS_] {sbs_wss,13} No sbs session found, disconnecting websocket
15:27:26.361 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 2500 rows
15:27:26.361 [warning] [_SBS_] {sbs_wss,13} No sbs session found, disconnecting websocket
15:27:27.718 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 3000 rows
15:27:29.185 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 3500 rows
15:27:29.325 [info] [_IMEM_] {imem_snap,783} snapshot created for tpacProd
15:27:30.651 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 4000 rows
15:27:32.055 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 4500 rows
15:27:33.428 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 5000 rows
15:27:34.816 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 5500 rows
15:27:36.236 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 6000 rows
15:27:37.765 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 6500 rows
15:27:39.122 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 7000 rows
15:27:39.418 [info] [_IMEM_] {imem_snap,783} snapshot created for tpacProd
15:27:40.526 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 7500 rows
15:27:41.961 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 8000 rows
15:27:43.365 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 8500 rows
15:27:44.785 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 9000 rows
15:27:46.251 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 9500 rows
15:27:47.655 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 10000 rows
15:27:49.059 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 10500 rows
15:27:49.543 [info] [_IMEM_] {imem_snap,783} snapshot created for tpacProd
15:27:50.432 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 11000 rows
15:27:51.805 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 11500 rows
15:27:53.240 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 12000 rows
15:27:54.675 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 12500 rows
15:27:56.080 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 13000 rows
15:27:57.499 [info] [_IMEM_] {imem_snap,573} restoring tpacProd updated 13500 rows
15:27:57.889 [info] [_IMEM_] {imem_snap,517} backup file "./snapshot/tpac.bkp" restored
15:27:57.889 [info] [_IMEM_] {imem_snap,454} Restored table tpac as tpacProd from ./snapshot/tpac.bkp with result {0,0,13648}
```
@stoch If https://github.com/K2InformaticsGmbH/dderl/pull/239/files and https://github.com/K2InformaticsGmbH/dderl/pull/247 you are thinking about then its only for histogram and only in `dderl_fsm`. Probably has not impact to snapshot/restore!

@shamis Can https://github.com/K2InformaticsGmbH/imem/pull/81 have an impact? -- please investigate.

**Comment by shamis** [comment] 2016-06-17 13:55
@c-bik The changes in #81 were made to capture the file handling errors. In this case file was accessible as 3500 records were read from it. I don't think changes in #81 could have caused this. Also the changes are in `restore_chunked` which is called from `restore_as`.

**Comment by c-bik** [comment] 2016-06-17 15:17
@acautin for DDerl side investigation!

**Comment by acautin** [comment] 2016-06-21 09:43
Unable to reproduce it at the moment, closing for now.

**Closed by acautin** 2016-06-21 09:43 UTC
Labels: bug
